### ISSUE TITLE
submitting registration returns json parse error

### ISSUE THREAD

**Issue by brimwd** [mafrides/usability-1#6]
Registration object is created and stored to database, but parse error is returned:
`"parsererror" SyntaxError: Unexpected end of JSON input`

Session availability is not set to `false`.

**Comment by brimwd** [comment]
Can be tested on test-data-5.js (creates a study with sessions today starting at 10PM)
test-data-5.js contains a study called "Today Study"

**Comment by mafrides** [comment]
Resolved
